openapi: 3.0.0
info:
  title: rkwst http
  version: 0.1.0
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.txt'
  description: RKWST http service for working with request nets
servers:
  - url: 'https://rkw.st/api/v1'
    description: RKWST v1 API
paths:
  /net:
    post:
      summary: Create net
      operationId: create-net
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Net'
              examples:
                example-create-net:
                  value:
                    id: ekd8
                    endpoint: ekd8.rwk.st
                    deadline: '2019-08-24T14:45:22Z'
                    requests: []
      description: Create new request net.
  '/nets/{id}':
    get:
      summary: Get net
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Net'
              examples:
                example-get-net:
                  value:
                    id: ekd8
                    endpoint: ekd8.rwk.st
                    deadline: '2019-08-24T14:45:22Z'
                    requests:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        ip: 192.168.0.1
                        proto: http
                        timestamp: '2019-08-24T14:25:22Z'
                        method: POST
                        uri: /path?query=param
                        path: /path
                        headers:
                          Content-Type:
                            - application/x-www-form-urlencoded
                          User-Agent:
                            - curl/7.84.0
                        form:
                          query:
                            - param
                          form:
                            - param
                        body: <base64 of body>
      operationId: get-net
      description: Get net info by its ID.
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: ID of net
    put:
      summary: Modify net
      operationId: modify-net
      responses:
        '200':
          description: OK
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                example-modify-net-error:
                  value: cannot extend the deadline further than 30mins from now
      description: Modify info about net. Currently only the deadline field is writable in order to extend the net lifetime.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Net'
        description: Description of this net with modified fields.
components:
  schemas:
    Request:
      title: Request
      x-stoplight:
        id: 9njw8o5ri88cl
      type: object
      description: Info about a single request to a specific Net.
      x-examples:
        example-request:
          id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
          ip: 192.168.0.1
          proto: http
          timestamp: '2019-08-24T14:15:22Z'
          method: POST
          uri: /path?a=1&a=2
          path: /path
          headers:
            Accept:
              - application/json
            Content-Type:
              - multipart/form-data
          form:
            a:
              - '1'
              - '2'
          files:
            attached-file:
              - filename: file.txt
                headers:
                  Content-Type:
                    - text/plain
                  Expires:
                    - '0'
                content: <base64 of file contents>
          body: <base64 of body>
      properties:
        id:
          type: string
          format: uuid
        ip:
          type: string
          format: ipv4
        proto:
          type: string
          enum:
            - http
            - https
        timestamp:
          type: string
          format: date-time
        method:
          type: string
        uri:
          type: string
          format: uri
        path:
          type: string
          format: uri-reference
        headers:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        form:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        files:
          type: object
          additionalProperties:
            type: array
            items:
              type: object
              properties:
                filename:
                  type: string
                headers:
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: string
                content:
                  type: string
                  format: byte
        body:
          type: string
          format: byte
    Net:
      title: Net
      x-stoplight:
        id: f6bswzsmm9o1i
      type: object
      description: Request net containing all the requests made to it.
      properties:
        id:
          type: string
          readOnly: true
        endpoint:
          type: string
          format: uri
          readOnly: true
        deadline:
          type: string
          format: date-time
        requests:
          type: array
          items:
            $ref: '#/components/schemas/Request'
          readOnly: true
    Error:
      type: string
      title: Error
      x-stoplight:
        id: n48wx3gw0repv
      description: Error message.
      example: error message
